### ISSUE TITLE
six requirement

### ISSUE THREAD

**Issue by jameswyse** [bennullgraham/filternaut#1]
I'm having trouble installing due to `install_requires=['six==1.9.0']`. My project depends on another library which does the same for `six>=1.10.0` which results in an impossible dependency graph.

Any way we can remove or adjust this requirement?

PS: Love the library, thanks!

**Comment by bennullgraham** [comment]
Thanks for the ticket jameswyse! The latest release on pypi (0.0.8) depends on six 1.9 or greater.
